name: 🚀 Promote DEV to PROD
on:
  workflow_dispatch:
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: 🚨 Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: 🤖 Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      - name: 🔀 Merge DEV into MAIN
        run: |
          git merge origin/dev --no-edit
          git push origin main